[package]
name = "memninja"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
egui = "0.25.0"
eframe = "0.25.0"
egui_tiles = "0.6.0"
hoodmem = { path = "../hoodmem" }
